# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meowpass < Formula
  desc "The secret vault for developers. CLI-first, E2E encrypted."
  homepage "https://meowpass.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chpecson/meowpass-releases/releases/download/v0.1.0/meowpass_0.1.0_darwin_amd64.tar.gz"
      sha256 "a1ff060aeee5fa8525e2d45c639463b02f364f7897c10c76f19d1df075e88f61"

      define_method(:install) do
        bin.install "meowpass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chpecson/meowpass-releases/releases/download/v0.1.0/meowpass_0.1.0_darwin_arm64.tar.gz"
      sha256 "f5f29e21f8bd73e01f4990b7695fdb651f153150de1ab5898c5a81241a8352e7"

      define_method(:install) do
        bin.install "meowpass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chpecson/meowpass-releases/releases/download/v0.1.0/meowpass_0.1.0_linux_amd64.tar.gz"
      sha256 "68093092d01bfdf6acfda7bed3d0b1e824f78b62a491e2cd95b72dd8dbde395f"
      define_method(:install) do
        bin.install "meowpass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chpecson/meowpass-releases/releases/download/v0.1.0/meowpass_0.1.0_linux_arm64.tar.gz"
      sha256 "2a7b075f9c3b38d62736e648b69286f40c89fa8af94ab4fb0446567ddad825ac"
      define_method(:install) do
        bin.install "meowpass"
      end
    end
  end
end
