# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meowpass < Formula
  desc "The secret vault for developers. CLI-first, E2E encrypted."
  homepage "https://meowpass.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chpecson/MeowPass/releases/download/v0.1.0/meowpass_0.1.0_darwin_amd64.tar.gz"
      sha256 "86a53d8831f05bf488e173dfad577e4dcf53e2278eea6e66998ffe1a606a1eba"

      define_method(:install) do
        bin.install "meowpass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chpecson/MeowPass/releases/download/v0.1.0/meowpass_0.1.0_darwin_arm64.tar.gz"
      sha256 "4f29401341908c70370c73f6a48ab3f29071e733c355d7e824358e9935c947e1"

      define_method(:install) do
        bin.install "meowpass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chpecson/MeowPass/releases/download/v0.1.0/meowpass_0.1.0_linux_amd64.tar.gz"
      sha256 "ca376ed37e144e15656799e8977c917c4b4ec2c9ed4e56d8c880d5eb81d4690f"
      define_method(:install) do
        bin.install "meowpass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chpecson/MeowPass/releases/download/v0.1.0/meowpass_0.1.0_linux_arm64.tar.gz"
      sha256 "231638d81a760d96313ff9d39377db1c3205966f70eadb25501e98794ebac34f"
      define_method(:install) do
        bin.install "meowpass"
      end
    end
  end
end
